name: Prod Integration
on:
  workflow_dispatch:
  # push:
  #   branches:
  #     - develop

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Download SFDX
        run: |
          echo Download SFDX
          curl https://developer.salesforce.com/media/salesforce-cli/sfdx/channels/stable/sfdx-linux-x64.tar.gz | tar -xz
          
      - name: Authorize Org
        run: |
          echo Authorize Org
          CONSUMER_KEY=${{ secrets.CONSUMER_KEY_INT }}
          USER_NAME=${{ secrets.USER_NAME_INT }}
          JWT_PATH=$GITHUB_WORKSPACE/devops/server.key
          # TODO
          # Implement encripted server.key
          ./sfdx/bin/sfdx auth:jwt:grant --clientid $CONSUMER_KEY --jwtkeyfile $JWT_PATH --username $USER_NAME

      - name: Run Tests
        run: |
          echo Run Tests
          USER_NAME=${{ secrets.USER_NAME_INT }}
          packageFilePath=$GITHUB_WORKSPACE/manifest/package.xml
          ./sfdx/bin/sfdx force:source:deploy -x $packageFilePath -w 100 -u $USER_NAME --checkonly --testlevel RunLocalTests --json

      - name: Run Deploy
        run: |
          echo Run Deploy
          USER_NAME=${{ secrets.USER_NAME_INT }}
          packageFilePath=$GITHUB_WORKSPACE/manifest/package.xml
          ./sfdx/bin/sfdx force:source:deploy -x $packageFilePath -w 100 -u $USER_NAME --testlevel RunLocalTests --json

      - name: Destructive Deploy
        run: |
          echo Destructive Deploy
          USER_NAME=${{ secrets.USER_NAME_INT }}
          destructiveFolderPath=$GITHUB_WORKSPACE/destructiveChanges
          ./sfdx/bin/sfdx force:mdapi:deploy -d $destructiveFolderPath -u $USER_NAME --ignorewarnings --testlevel RunLocalTests --json

      - name: Logout
        run: |
          echo Logout
          ./sfdx/bin/sfdx force:auth:logout -a -p